name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: List contents of the directory
        run: ls -R ./

      # Adicione o comando 'dotnet build' com o curinga para todos os projetos .csproj
      - name: Build
        run: dotnet build --no-restore */*.csproj --verbosity normal

      - name: Test
        run: dotnet test --no-build --verbosity normal
